### ISSUE TITLE
template not working

### ISSUE THREAD

**Issue by Boter316** [rubensworks/CustomMealery#1]
so for mods like this before i get into making my own stuff i'll first run the template and tweak it, but when i do i get an error, this is using the template you provided in the mod:

Template Used:
{
    nameid: "shinyBread",
    name: "Shiny Bread",
    texture: "minecraft:diamond",
    colorOverlay: {
        red: 150,
        green: 255,
        blue: 100
    },
    eatTime: 12,
    healAmount: 2,
    saturationModifier: 0.3,
    
    isWolfsFavoriteMeat: false,
    rarity: "epic",
    hasEffect: true,
    
    isAlwaysEdible: true,
    maxStackSize: 16,
    
    potionEffects: 
    [
        {
            potionid: 1,
            probability: 1.0,
            duration: 3,
            amplifier: 2
        },
        
        {
            potionid: 2,
            probability: 1.0,
            duration: 5,
            amplifier: 2
        }
    ],
    
    craftingRecipe: {
        recipeResultAmount: 4,
        recipe:
        [
            " , , ",
            "apple,diamond,plankWood",
            "diamond:1,apple,someMod:someItem:6"
        ]
    },
    
    furnaceRecipe: {
        recipeResultAmount: 4,
        inputnameid: "apple",
        inputmeta: 1,
        experience: 4
    }
}

Crash Report:
https://pastebin.com/1vyegsC5

**Comment by Boter316** [comment]
normally i can get a "malformed json" error as well as a hint at my problem, but i cannot discern it here

I am also aware you may not even care about this mod, just in case you do though

**Comment by rubensworks** [comment]
Sorry, this mod is not being updated anymore. Don't know what the cause of this could be.
